[package]
name = "xan"
version = "0.25.0"  #:version
authors = [
  "Andrew Gallant <jamslam@gmail.com>",
  "Guillaume Plique <guillaume.plique@sciencespo.fr>",
  "Béatrice Mazoyer <beatrice.mazoyer@sciencespo.fr>",
  "Laura Miguel <laura.miguel@sciencespo.fr>",
  "César Pichon <cesar.pichon@sciencespo.fr>",
  "Anna Charles <anna.charles@sciencespo.fr>",
]
description = "The CSV magician"
documentation = "https://github.com/medialab/xan#readme"
homepage = "https://github.com/medialab/xan"
repository = "https://github.com/medialab/xan"
readme = "README.md"
keywords = ["csv", "tsv", "cli"]
license = "Unlicense OR MIT"
autotests = false
edition = "2021"
include = [
  "Cargo.toml",
  "README.md",
  "LICENSE-MIT",
  "UNLICENSE",
  "src/**/*.rs",
  "src/**/*.pest",
  "tests/**/*.rs"
]

[[bin]]
name = "xan"
test = true
bench = false
doctest = false

[[test]]
name = "tests"

[dependencies]
arrayvec = "0.7.4"
atty = "0.2.14"
bstr = "1.10.0"
byteorder = "1"
bytesize = "1.3.0"
calamine = "0.24.0"
colored = "2.0.0"
console = "0.15.8"
crossbeam-channel = "0.2.4"
csv = "1.2.2"
csv-index = "0.1.6"
ctrlc = "3.4.4"
deepsize = "0.2.0"
dlv-list = "0.5.2"
docopt = "1"
emojis = "0.6.1"
encoding = "0.2.33"
ext-sort = { version = "0.1.4", features = ["memory-limit"] }
filetime = "0.1"
flate2 = "1.0.27"
glob = "0.3.1"
indexmap = "2.5.0"
indicatif = "0.17.8"
jiff = "0.1.13"
lazy_static = "1.4.0"
md5 = "0.7.0"
namedlock = "0.7.0"
numfmt = "1.1.1"
num_cpus = "1.4"
ordered-float = "4.2.2"
paltoquet = "0.10.0"
pariter = "0.5.1"
pest = "2.7.11"
pest_derive = "2.7.11"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_seeder = "0.2.3"
ratatui = { version = "0.28.1", default-features = false }
rayon = "1.8.0"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1.0"
toml = "0.8.19"
termsize = "0.1.8"
textwrap = "0.16.1"
threadpool = "1.3"
thread_local = "1.1.8"
transient-btree-index = "0.5.1"
unidecode = "0.3.0"
unicode-segmentation = "1.10.1"
unicode-width = "0.1.11"
uuid = { version = "0.8.2", features = ["v4"] }

# NOTE: pager does not work on windows
[target.'cfg(not(windows))'.dependencies]
pager = "0.16.1"
